### ISSUE TITLE
LOGGER - Ensure that we are able to log radar/dsrc data separately

### ISSUE THREAD

**Issue by rsyvarth** [rsyvarth/dsrc-radar-collision-avoidance#6]
In order for our current design to work, we need to be able to write/read from the dsrc/radar/final data logs separately. We can either do this by writing to different files at application run time or by having some method of separating the data out later so we can run our log parsing separately.

**Comment by rsyvarth** [comment]
The logging logic for this called from `RadarDataParser::run` and `DsrcDataParser::run`

**Comment by bsarden** [comment]
With the Python Logger module, you can configure different loggers in the same conf files. We could possibly route logs to different log files doing that
